### ISSUE TITLE
Set Up hybris B2C accelerator using HSQL db

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_sergei#1]
As a **Developer**
I want to have local hybris environment with B2C accelerator (on HSQL db), 
So that I could work with hybris platform on my local machine

**AC:**
1) hybris installed
2) hybris built
3) hybris initialized
4) checkout process could be successfully done

_Tips:_
How to install -- https://wiki.hybris.com/display/tr52/Telco+Accelerator
Development environment setup example -- https://kb.epam.com/display/ECOMCC/Dev-Environment+Setup+for+iPromoTarget+project
EPAM how-to -- https://kb.epam.com/display/ECOMCC/Platform+Installation+Instructions

**Comment by AlagosZim** [comment]
![telco_order](https://cloud.githubusercontent.com/assets/7558073/22473949/1cb2965a-e7e3-11e6-9e75-c7bf4f26acb1.PNG)
