### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_sergei#16]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.

_Tips:_
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by AlagosZim** [comment]
![image](https://cloud.githubusercontent.com/assets/7558073/24142792/60cad988-0e30-11e7-9bc0-0dd809a57ded.png)
