### ISSUE TITLE
Organization customers receive e-mails

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_sergei#20]
As an **organization manager**
I want to be on the same page with organization contents
So that I receive daily email with list of users in my organization

**AC**
Email is sent to each organization manager whose address is set as an Organization.email attribute.
The email should contain list of all users in this organization.

**Mail server configuration**
```
mail.from=<your email>
mail.replyto=<your email>
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=<your email>
mail.smtp.password=<your email account password>
mail.smtp.starttls.enable=true
mail.use.tls=true
```

**Comment by AlagosZim** [comment]
![organisationemail](https://cloud.githubusercontent.com/assets/7558073/24473457/0222831a-14d2-11e7-96e2-e473aaa60bad.PNG)

**Comment by AlagosZim** [comment]
![image](https://cloud.githubusercontent.com/assets/7558073/24474572/aebec9c8-14d5-11e7-81a0-111e53fb65c1.png)

![organisationemail](https://cloud.githubusercontent.com/assets/7558073/24474499/7e199dac-14d5-11e7-8f36-d863e0dac28b.PNG)
