### ISSUE TITLE
Obtain list of organizations via webservices

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_sergei#22]
As a **mobile developer or developer of integration candidate utility**
I want to have a possibility to obtain list of organizations via REST calls
So that webservices extension is configured properly

**AC**
Webservices extension is turned-on for B2C accelerator
Appropriate controllers are written
jUnit tests are written to test the functionality

_Tips:_
https://wiki.hybris.com/display/release5/Introduction+to+Web+Services
https://wiki.hybris.com/display/release5/Key+Features+and+Implementation+Details

**Comment by AlagosZim** [comment]
![image](https://cloud.githubusercontent.com/assets/7558073/26420863/a2bfa412-40cc-11e7-9868-bd06ea9df087.png)
