### ISSUE TITLE
Generate an error message when organization name length is greater than 15 simbols

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_sergei#26]
As a **content manager**
I want to have a constraint for organization's name attribute
So that an appropriate constraint is created via ImpEx and is available in Admin cockpit.

**AC**
Aftert an attempt to set a long value for organization name an appropriate constraint generated an error
Constraint is created using ImpEx and could be changed in Admin cockpit

_Tips:_
https://wiki.hybris.com/display/R5T/Trail+~+Validation

**Comment by AlagosZim** [comment]
![image](https://user-images.githubusercontent.com/7558073/27302035-0b522bc8-553e-11e7-89c3-a704513b4f56.png)
